// Generated by Supabase MCP — do not edit manually
// Regenerate: mcp__supabase__generate_typescript_types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      brands: {
        Row: { created_at: string; id: string; name: string; shop_id: string; updated_at: string }
        Insert: { created_at?: string; id?: string; name: string; shop_id: string; updated_at?: string }
        Update: { created_at?: string; id?: string; name?: string; shop_id?: string; updated_at?: string }
        Relationships: [{ foreignKeyName: "brands_shop_id_fkey"; columns: ["shop_id"]; isOneToOne: false; referencedRelation: "shops"; referencedColumns: ["id"] }]
      }
      categories: {
        Row: { created_at: string; id: string; name: string; position: number; shop_id: string; type: string; updated_at: string }
        Insert: { created_at?: string; id?: string; name: string; position?: number; shop_id: string; type?: string; updated_at?: string }
        Update: { created_at?: string; id?: string; name?: string; position?: number; shop_id?: string; type?: string; updated_at?: string }
        Relationships: [{ foreignKeyName: "categories_shop_id_fkey"; columns: ["shop_id"]; isOneToOne: false; referencedRelation: "shops"; referencedColumns: ["id"] }]
      }
      category_attributes: {
        Row: { category_id: string; created_at: string; format: string; id: string; name: string; options: Json | null; position: number; required: boolean; scope: string; updated_at: string }
        Insert: { category_id: string; created_at?: string; format?: string; id?: string; name: string; options?: Json | null; position?: number; required?: boolean; scope?: string; updated_at?: string }
        Update: { category_id?: string; created_at?: string; format?: string; id?: string; name?: string; options?: Json | null; position?: number; required?: boolean; scope?: string; updated_at?: string }
        Relationships: [{ foreignKeyName: "category_attributes_category_id_fkey"; columns: ["category_id"]; isOneToOne: false; referencedRelation: "categories"; referencedColumns: ["id"] }]
      }
      product_attribute_values: {
        Row: { attribute_id: string; created_at: string; id: string; product_id: string; updated_at: string; value: string | null }
        Insert: { attribute_id: string; created_at?: string; id?: string; product_id: string; updated_at?: string; value?: string | null }
        Update: { attribute_id?: string; created_at?: string; id?: string; product_id?: string; updated_at?: string; value?: string | null }
        Relationships: [
          { foreignKeyName: "product_attribute_values_attribute_id_fkey"; columns: ["attribute_id"]; isOneToOne: false; referencedRelation: "category_attributes"; referencedColumns: ["id"] },
          { foreignKeyName: "product_attribute_values_product_id_fkey"; columns: ["product_id"]; isOneToOne: false; referencedRelation: "products"; referencedColumns: ["id"] }
        ]
      }
      product_units: {
        Row: { created_at: string; id: string; label: string; product_id: string; status: string; updated_at: string }
        Insert: { created_at?: string; id?: string; label: string; product_id: string; status?: string; updated_at?: string }
        Update: { created_at?: string; id?: string; label?: string; product_id?: string; status?: string; updated_at?: string }
        Relationships: [{ foreignKeyName: "product_units_product_id_fkey"; columns: ["product_id"]; isOneToOne: false; referencedRelation: "products"; referencedColumns: ["id"] }]
      }
      products: {
        Row: { brand_id: string | null; category_id: string; created_at: string; description: string | null; id: string; image_url: string | null; name: string; price_shop: number; price_web: number; shop_id: string; updated_at: string }
        Insert: { brand_id?: string | null; category_id: string; created_at?: string; description?: string | null; id?: string; image_url?: string | null; name: string; price_shop?: number; price_web?: number; shop_id: string; updated_at?: string }
        Update: { brand_id?: string | null; category_id?: string; created_at?: string; description?: string | null; id?: string; image_url?: string | null; name?: string; price_shop?: number; price_web?: number; shop_id?: string; updated_at?: string }
        Relationships: [
          { foreignKeyName: "products_brand_id_fkey"; columns: ["brand_id"]; isOneToOne: false; referencedRelation: "brands"; referencedColumns: ["id"] },
          { foreignKeyName: "products_category_id_fkey"; columns: ["category_id"]; isOneToOne: false; referencedRelation: "categories"; referencedColumns: ["id"] },
          { foreignKeyName: "products_shop_id_fkey"; columns: ["shop_id"]; isOneToOne: false; referencedRelation: "shops"; referencedColumns: ["id"] }
        ]
      }
      profiles: {
        Row: { avatar_url: string | null; created_at: string; first_name: string | null; id: string; last_name: string | null; onboarding_current_step: number; role: Database["public"]["Enums"]["user_role"]; shop_id: string | null; updated_at: string }
        Insert: { avatar_url?: string | null; created_at?: string; first_name?: string | null; id: string; last_name?: string | null; onboarding_current_step?: number; role?: Database["public"]["Enums"]["user_role"]; shop_id?: string | null; updated_at?: string }
        Update: { avatar_url?: string | null; created_at?: string; first_name?: string | null; id?: string; last_name?: string | null; onboarding_current_step?: number; role?: Database["public"]["Enums"]["user_role"]; shop_id?: string | null; updated_at?: string }
        Relationships: [{ foreignKeyName: "profiles_shop_id_fkey"; columns: ["shop_id"]; isOneToOne: false; referencedRelation: "shops"; referencedColumns: ["id"] }]
      }
      shops: {
        Row: { address: string | null; created_at: string; email: string | null; id: string; logo_url: string | null; name: string; onboarding_completed: boolean; phone: string | null; siret: string | null; slug: string; stripe_connect_id: string | null; stripe_subscription_id: string | null; subscription_active: boolean; tva_number: string | null; updated_at: string }
        Insert: { address?: string | null; created_at?: string; email?: string | null; id?: string; logo_url?: string | null; name: string; onboarding_completed?: boolean; phone?: string | null; siret?: string | null; slug: string; stripe_connect_id?: string | null; stripe_subscription_id?: string | null; subscription_active?: boolean; tva_number?: string | null; updated_at?: string }
        Update: { address?: string | null; created_at?: string; email?: string | null; id?: string; logo_url?: string | null; name?: string; onboarding_completed?: boolean; phone?: string | null; siret?: string | null; slug?: string; stripe_connect_id?: string | null; stripe_subscription_id?: string | null; subscription_active?: boolean; tva_number?: string | null; updated_at?: string }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      get_user_role: { Args: never; Returns: Database["public"]["Enums"]["user_role"] }
      get_user_shop_id: { Args: never; Returns: string }
    }
    Enums: { user_role: "owner" | "employee" }
    CompositeTypes: { [_ in never]: never }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  T extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"]) | { schema: keyof DatabaseWithoutInternals },
  N extends T extends { schema: keyof DatabaseWithoutInternals } ? keyof (DatabaseWithoutInternals[T["schema"]]["Tables"] & DatabaseWithoutInternals[T["schema"]]["Views"]) : never = never,
> = T extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[T["schema"]]["Tables"] & DatabaseWithoutInternals[T["schema"]]["Views"])[N] extends { Row: infer R } ? R : never
  : T extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[T] extends { Row: infer R } ? R : never
    : never

export type TablesInsert<
  T extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  N extends T extends { schema: keyof DatabaseWithoutInternals } ? keyof DatabaseWithoutInternals[T["schema"]]["Tables"] : never = never,
> = T extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[T["schema"]]["Tables"][N] extends { Insert: infer I } ? I : never
  : T extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][T] extends { Insert: infer I } ? I : never
    : never

export type TablesUpdate<
  T extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  N extends T extends { schema: keyof DatabaseWithoutInternals } ? keyof DatabaseWithoutInternals[T["schema"]]["Tables"] : never = never,
> = T extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[T["schema"]]["Tables"][N] extends { Update: infer U } ? U : never
  : T extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][T] extends { Update: infer U } ? U : never
    : never

export type Enums<
  T extends keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  N extends T extends { schema: keyof DatabaseWithoutInternals } ? keyof DatabaseWithoutInternals[T["schema"]]["Enums"] : never = never,
> = T extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[T["schema"]]["Enums"][N]
  : T extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][T]
    : never

export const Constants = { public: { Enums: { user_role: ["owner", "employee"] } } } as const
